-- QUICK FIX: Foreign Key Type Mismatch Error
-- Run this if you get: "Key columns are of incompatible types: bigint and uuid"

-- Step 1: Check current types
select 
  table_name, 
  column_name, 
  data_type 
from information_schema.columns 
where table_schema = 'public' 
  and column_name = 'id'
  and table_name in ('cities', 'streets', 'organizations', 'businesses', 'stories');

-- If any show 'uuid', continue with Step 2
-- If all show 'bigint', your tables are correct - skip to Step 4

-- Step 2: Drop ALL foreign key constraints first
alter table stories drop constraint if exists stories_rua_id_fkey;
alter table stories drop constraint if exists stories_org_id_fkey;
alter table stories drop constraint if exists stories_negocio_id_fkey;
alter table streets drop constraint if exists streets_cidade_id_fkey;

-- Step 3: Drop ALL foreign key columns (prevents dependency errors)
alter table stories drop column if exists rua_id;
alter table stories drop column if exists org_id;
alter table stories drop column if exists negocio_id;
alter table streets drop column if exists cidade_id;

-- Step 4: Convert UUID to bigint (now safe - no dependencies)

-- Cities
alter table cities drop constraint if exists cities_pkey;
alter table cities drop column if exists id;
alter table cities add column id bigint generated by default as identity primary key;

-- Organizations
alter table organizations drop constraint if exists organizations_pkey;
alter table organizations drop column if exists id;
alter table organizations add column id bigint generated by default as identity primary key;

-- Businesses
alter table businesses drop constraint if exists businesses_pkey;
alter table businesses drop column if exists id;
alter table businesses add column id bigint generated by default as identity primary key;

-- Streets
alter table streets drop constraint if exists streets_pkey;
alter table streets drop column if exists id;
alter table streets add column id bigint generated by default as identity primary key;

-- Stories
alter table stories drop constraint if exists stories_pkey;
alter table stories drop column if exists id;
alter table stories add column id bigint generated by default as identity primary key;

-- Step 5: Recreate foreign key columns as bigint

-- streets.cidade_id
alter table streets add column cidade_id bigint;
alter table streets add constraint streets_cidade_id_fkey
  foreign key (cidade_id) references cities(id) on delete set null;

-- stories.rua_id
alter table stories add column rua_id bigint;
alter table stories add constraint stories_rua_id_fkey
  foreign key (rua_id) references streets(id) on delete set null;

-- stories.org_id
alter table stories add column org_id bigint;
alter table stories add constraint stories_org_id_fkey
  foreign key (org_id) references organizations(id) on delete set null;

-- stories.negocio_id
alter table stories add column negocio_id bigint;
alter table stories add constraint stories_negocio_id_fkey
  foreign key (negocio_id) references businesses(id) on delete set null;

-- Done! All tables now use bigint for IDs and foreign keys
